INSERT INTO `classify_info` (`id`, `name`) VALUES (1, '人类学');
INSERT INTO `classify_info` (`id`, `name`) VALUES (2, '历史学');
INSERT INTO `classify_info` (`id`, `name`) VALUES (3, '社会学');
INSERT INTO `classify_info` (`id`, `name`) VALUES (4, '科学');
INSERT INTO `classify_info` (`id`, `name`) VALUES (5, '法学');
INSERT INTO `classify_info` (`id`, `name`) VALUES (6, '名人传记');
INSERT INTO `classify_info` (`id`, `name`) VALUES (7, '技术');
INSERT INTO `classify_info` (`id`, `name`) VALUES (8, '历史学');
INSERT INTO `classify_info` (`id`, `name`) VALUES (9, '伦理学');
